#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

import docker
import grpc
import re
import os
from pathlib import Path
from typing import Dict
from chirpstack_api.api import application_pb2, application_pb2_grpc, tenant_pb2, tenant_pb2_grpc

# --- Configuration ---
PATTERN = "chirpstack-init"
CHIRPSTACK_SERVER = "chirpstack:8080"
APP_NAME = "wise-os-app"
APP_DESCRIPTION = "created automatically from docker"
TENANT_ID = ""
ENV_FILE_PATH = os.environ.get("CHIRPSTACK_ENV_FILE", "/workspace/.env.runtime")
REQUIRED_KEYS = ("CHIRPSTACK_API_KEY", "CHIRPSTACK_TENANT_ID", "CHIRPSTACK_APP_ID")


# --- Utils: .env parsing ---
def _normalize_newlines(path: Path) -> None:
    if not path.exists():
        return
    raw = path.read_bytes()
    new = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    if new != raw:
        path.write_bytes(new)

def load_env_file(path: Path) -> Dict[str, str]:
    data: Dict[str, str] = {}
    if not path.exists():
        return data
    _normalize_newlines(path)
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip()
    return data

def is_env_valid(env: Dict[str, str]) -> bool:
    for k in REQUIRED_KEYS:
        if k not in env:
            return False
        v = env[k]
        if v is None or v.strip() == "":
            return False
    return True

def write_env_atomic(path: Path, new_vars: Dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = load_env_file(path)
    existing.update(new_vars)

    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# ChirpStack Configuration\n")
        f.write("# Auto-generated by main.py\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")
    os.replace(tmp, path)  # atomic on POSIX
    print(f"Environment variables written to {path}")
    for k in REQUIRED_KEYS:
        val = existing.get(k, "")
        preview = (val[:40] + "...") if len(val) > 43 else val
        print(f"   {k}={preview}")


# --- ChirpStack helpers ---
def get_api_key_from_container() -> str:
    client = docker.from_env()
    print("Creating API key inside the ChirpStack container...")
    cmd = 'chirpstack --config /etc/chirpstack create-api-key --name "auto-key"'
    containers = [
        c for c in client.containers.list(all=True)
        if PATTERN in c.name
    ]
    for container in containers:
        exec_log = client.containers.get(container).exec_run(cmd)
    output = exec_log.output.decode()
    print(output)

    match = re.search(r"token:\s*([A-Za-z0-9_\-\.]+)", output)
    if not match:
        raise RuntimeError("Failed to retrieve token from CLI output.")
    token = match.group(1).strip()
    print(f"API key retrieved:\n{token[:40]}... (truncated)")
    return token

def get_tenant_id(channel, metadata) -> str:
    tenants = tenant_pb2_grpc.TenantServiceStub(channel)
    resp = tenants.List(tenant_pb2.ListTenantsRequest(limit=1, offset=0), metadata=metadata)
    if not resp.result:
        raise RuntimeError("No tenants found — create a tenant first (TenantService.Create).")
    return resp.result[0].id

def create_application(api_key: str):
    md = [('authorization', f'Bearer {api_key}')]
    channel = grpc.insecure_channel(CHIRPSTACK_SERVER)

    tenant_id = TENANT_ID or get_tenant_id(channel, md)
    apps = application_pb2_grpc.ApplicationServiceStub(channel)
    app = application_pb2.Application(
        name=APP_NAME,
        description=APP_DESCRIPTION,
        tenant_id=tenant_id,
    )
    req = application_pb2.CreateApplicationRequest(application=app)
    res = apps.Create(req, metadata=md)

    print("Application created:")
    print("   ID:", res.id)
    print("   Tenant:", tenant_id)
    return res.id, tenant_id


# --- Main flow ---
def main():
    env_path = Path(ENV_FILE_PATH)
    force_regen = os.environ.get("FORCE_REGEN", "").lower() in ("1", "true", "yes")

    current = load_env_file(env_path)
    if is_env_valid(current) and not force_regen:
        print(f"{env_path} already exists and is valid. Skipping regeneration.")
        for k in REQUIRED_KEYS:
            v = current.get(k, "")
            preview = (v[:40] + "...") if len(v) > 43 else v
            print(f"   {k}={preview}")
        return

    print("Generating / refreshing ChirpStack credentials...")
    token = get_api_key_from_container()
    app_id, tenant_id = create_application(token)

    write_env_atomic(env_path, {
        "CHIRPSTACK_API_KEY": token,
        "CHIRPSTACK_TENANT_ID": tenant_id,
        "CHIRPSTACK_APP_ID": app_id,
    })

    saved = load_env_file(env_path)
    if not is_env_valid(saved):
        raise RuntimeError(f"Saved {env_path} is invalid after write.")
    print("Validation OK – .env.runtime is present and complete.")

if __name__ == "__main__":
    main()