name: Check MPL License

on:
  pull_request:
  push:
    branches:
      - main
      - 'stabilization/*'
      - dev

jobs:
  check-license:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
    # - name: LICENSE Existence Checker
    #   uses: Gary-H9/license-existence-checker@v1.0.0
